### ISSUE TITLE
Not installable via `npm`

### ISSUE THREAD

**Issue by briandipalma** [systemjs/plugin-text#1]
Considering this module is so small I wonder if there isn't an imperitive way of configuring SystemJS to use a plugin?

```js
System.plugins.txt = {
    instantiate = function(load) {
       return load.source;
    }
}
```

Although it should still be available via `npm`.

**Comment by briandipalma** [comment]
Closing as I'd install this via JSPM not npm.

**Comment by thelinuxlich** [comment]
jspm install text is not working for me
