### ISSUE TITLE
Fork Plugin to Create plugin-html

### ISSUE THREAD

**Issue by nkoterba** [systemjs/plugin-text#10]
Hi -

Would there be in any interest in creating a `plugin-html` SystemJS plugin by forking this repo and allowing .html endings to by default be treated as text?

I'm currently using this plugin to inline html files. I'm switching from Browserify/CommonJS so have a lot of:
`require('../somepath/myfile.html')

throughout the code base and would prefer not to have to append !text to all those locations.  It would be nice if there was a plugin-html that worked just like text-html but accepted .html file endings by default.

I can do this if you think it's worthwhile or I'm not missing some configuration variable or flag that I could set to do this...

Thanks!

**Comment by guybedford** [comment]
You can alias the text plugin as html if you like on install - `jspm install html=text`.

**Comment by nkoterba** [comment]
@guybedford 

So `jspm install html=text` gave me the following error:

```javascript
nk-mbp:webclient nkoterba$ jspm install html=text
     Updating registry cache...

err  Repo jspm:html not found!

warn Installation changes not saved.
```

I then tried `jspm install html=jspm:text` which did install and correctly update System.config.map:
```javascript
"html": "github:systemjs/plugin-text@0.0.2",
```

However, when I remove the `!text` endings to my require statements i get the following in the browser console:
```javascript
GET http://localhost:8080/scripts/directives/device-info/device-info.html.js 404 (Not Found)
```

It's appending **.js** to the end of the html file.

Am I doing something wrong here?

Here's a sample require/import statmenet:
```javascript
template: require('./device-info.html'), // inline html using plugin
```

**Comment by guybedford** [comment]
Make sure you are running on the latest version of jspm.

**Comment by nkoterba** [comment]
@guybedford Ok...updated! Forgot that I should probably keep updating.

So `jspm install html=text` now works.

However, I still get 404 errors b/c it's appending .js to the .html files:
```javascript
"Potentially unhandled rejection [3] Error loading "scripts/modules/dialogs/upload/upload.html" at http://localhost:8080/scripts/modules/dialogs/upload/upload.html.js
Error loading "scripts/modules/dialogs/upload/upload.html" from "app" at http://localhost:8080/app.js
Not Found: http://localhost:8080/scripts/modules/dialogs/upload/upload.html.js (WARNING: non-Error used)"
```

I have verified that if I append `!html` it does work, e.g.:
```javascript
template: require('./upload/upload.html!html'),
```

But as stated above, trying to avoid that...

**Comment by guybedford** [comment]
The only saving you'll get here is via `require('./upload/upload.html!')`, where the plugin module is inferred from the extension name. In future there will be support for setting this via configuration.

**Comment by nkoterba** [comment]
@guybedford Ah ok.

Makes sense. I misread the css-plugin page where it showed appending the **!**.

I thought by default the system would check require/import paths to see if the path ended with any known extension (e.g. .html, .css, .less, .scss) and if one matched, it would apply the plugin automatically.

Looks like I'll just append `!` or `!html`.

Sorry for the confusion.  Closing the issue.
