### ISSUE TITLE
Byte Order Mark being included when bundling text dependencies with minification enabled

### ISSUE THREAD

**Issue by jonoward** [systemjs/plugin-text#11]
When using systemjs-builder together with a text dependency, if the text file has a Byte-Order-Mark, this is being included in the generated output of this plugin. Normally this doesn't cause an issue, but if you have minification enabled, this gets encoded, so you land up with \ufeff being included at the beginning of the string:

`.exports="\ufeff<div>hello</div>"`

This issue started appearing around 2 weeks after there was a commit to UglifyJS (https://github.com/mishoo/UglifyJS2/commit/10c7f52074718b506d9ebfe5cc5a9c7dd9c25b5a) that changed the behaviour to only remove the BOM at the begining of the file, where as before it stripped it out globally (which is probably a fair change, the BOM should only be present at the begining of the file). I.e. I think the behaviour of Uglify was masking this issue.

I'm going to submit a small PR to strip this BOM out - let me know if you don't think this project is the place for it. Thanks!

**Comment by guybedford** [comment]
Thanks for posting and offering to contribute. Let's rather catch this properly in https://github.com/ModuleLoader/es6-module-loader/blob/master/src/system-fetch.js#L68?

**Comment by jonoward** [comment]
Sure sounds good, are you thinking just to do something like:
`fulfill((data + '').replace(/^[\ufeff]/, ''));` ?
Have tried this locally, seems to resolve the issue. Is is safe to always strip the BOM?

**Comment by guybedford** [comment]
Yes I believe so. May be best to do a `dataString[0] == '\efeff'` check directly instead of a regex, although probably doesn't matter that much.

**Comment by jonoward** [comment]
ok cool. I'll make a PR for it over in es-module-loader

**Comment by jonoward** [comment]
Have opened a new issue at https://github.com/ModuleLoader/es6-module-loader/issues/388 , am closing this one
