### ISSUE TITLE
Export text as default

### ISSUE THREAD

**Issue by subesokun** [systemjs/plugin-text#12]
When compiling following code
```javascript
import template from './template.html';
console.log(template);
```
via the TS compiler it always produces a code like
```javascript
var template = require('./template.html');
console.log(template.default);
```
So I'm wondering if the text should be exported always as `module.exports.default` or if the behavior of the TS compiler is not correct?

**Comment by guybedford** [comment]
@subesokun I'd suggest rather use the System.register output of TypeScript now for compatibility.

**Comment by guybedford** [comment]
But yes, that output is incorrect in TypeScript for compatibility.

**Comment by subesokun** [comment]
Great, thanks for the tip. I didn't know yet that there is a special `format: 'system'` configuration for the TS compiler. Using that it works now.
