### ISSUE TITLE
Doesn't work with typescript

### ISSUE THREAD

**Issue by robertbaker** [systemjs/plugin-text#14]
I tried it but typescript 1.5.3+ doesn't like `import somethingHTML from 'components/something/something.html!text';` complains it can't find a module.

`import  'components/something/something.html!text';`
would work but not usable since I can't assign it to anything.

**Comment by robertbaker** [comment]
@guybedford

**Comment by robertbaker** [comment]
The css plugin doesn't have this issue...

**Comment by guybedford** [comment]
I believe this is a limitation in TypeScript. It may be worth investigating using the TypeScript plugin instead at https://github.com/frankwallis/plugin-typescript if that doesn't have this issue.

**Comment by robertbaker** [comment]
@guybedford  I used that plugin, which doesn't have that issue. It might be typescript. It would work if you didn't use a var or a named export, but you need to for using it with angular template.

**Comment by kburson** [comment]
And to assign directly to an angular template field.

**Comment by kburson** [comment]
I am keen to migrate to Typescript now that 1.5.x has been released with ES6 module support, but this could be a blocker, although there are workarounds...

**Comment by Hotell** [comment]
@robertbaker @kburson 
`import somethingHTML from 'components/something/something.html!text';` doesn't and won't  work because `something.html!text` is not a es6 module and it doesn't has default export.

`import 'components/something/something.html!text';` works because that's valid es6 module syntax known as "empy import".

http://www.2ality.com/2014/09/es6-modules-final.html

so this issue can be closed IMHO as **wont fix**, because it's unsolvable at this moment. 

I think it's required to add some feature to typescript compiler, to understand this special syntax, and export some default, so it can be consumed in default es6 module import.

**Comment by born2net** [comment]
+1 any workaround?

**Comment by robertbaker** [comment]
I haven't used typescript since 1.7. This may be fixable in TS 1.9 but I don't know. I will close this since it is/was a typescript limitation.

**Comment by Emigre** [comment]
Perhaps this feature of Typescript 2.0 can help with this?
[Support shorthand ambient module declarations and wildcard chars in module names](https://github.com/Microsoft/TypeScript/issues/6615)
[Wildcard character in module names](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#wildcard-character-in-module-names)
```typescript
// styles.d.ts
declare module "*.html" {
  const value: any;
  export default value;
}
```
I have not been able to make it work, though.

**Comment by mmatczak** [comment]
I could make it work in Angular 2.4.4 / Typescript 2.1.5 / SystemJS 0.19.40:

```javascript
// declarations.d.ts
declare module '*!text' {
  export default '';
}
```

```javascript
// my-component.component.ts
/// <reference path="declarations.d.ts" />
import {Component} from '@angular/core';
import * as template from './my-component.component.html!text';

@Component({
  selector: 'my-component',
  template: template + ''
})
export class MyComponent {
}
```

**Comment by aluanhaddad** [comment]
@mmatczak indeed that will work well.

However, using 
```js
SystemJS.config({
  packages: {
    "app": {
      "meta": {
        "*.html": {
          "loader": "text"
        }
      }
   }
}
```
along with 
```ts
// declarations.d.ts
declare module '*.html' {
  export default '';
}
```
is preferable as it abstracts out any dependency on the plugin syntax and on the specific plugin from module specifier, leading to easier maintenance and more readable code.
