### ISSUE TITLE
With Karma tests

### ISSUE THREAD

**Issue by linnett** [systemjs/plugin-text#15]
I've managed to get this plugin to work really well with directives but when I try and use it in a karma test, it doesn't seem to work (I am using JSPM).

import t from './template.html!text';

This doesn't work, so I tried importing the plugin at the top too:

import 'systemjs/plugin-text';
import t from './template.html!text';

This too doesn't work. Is there something else I need to do to enable this to work? There is no error unfortunately - the tests just do not ever run. Thanks

**Comment by linnett** [comment]
Can anyone please help with this?

**Comment by guybedford** [comment]
This sounds like a Karma issue, I really can't assist with that unfortunately.

**Comment by linnett** [comment]
Thanks for the response @guybedford. Just out of interest, are you using Karma testing and if so, how do you get the templates loaded into your tests? Thanks

**Comment by guybedford** [comment]
I don't use Karma with SystemJS, it's something I've had to rely on the community to provide as I don't personally have the resources to work on this problem as well.

**Comment by linnett** [comment]
Thanks Guy. I've posted another ticket in the JSPM Karma.

**Comment by davinkevin** [comment]
Very important for us too...
