### ISSUE TITLE
Bundling sets wrong paths for text templates

### ISSUE THREAD

**Issue by calvinfroedge** [systemjs/plugin-text#16]
First off, thanks for the great tools...and for what it's worth, I know that bundling the jade compiler is a horrible idea (few hundred kb)...however, this is a more general problem with the text plugin (or my understanding of source paths with systemjs):

src/app.js
```
import jade from "jade";
import template from 'test.jade!text';
```

Bundling...
```
jspm bundle-sfx --minify src/app dist/build
```

Relevant Configuration:
```
  paths: {
    "*": "src/*",
    "*.jade": "src/templates/*.jade"
  }
```

Yields:
```
err  Error: ENOENT, open '/Users/calvinfroedge/Code/Projects/oss/front.js/src/templates/src/templates/test.jade'
         at Error (native)
I can resolve the issue by removing the "*": "src/*" path, but then I need to load everything by its full path.
```

**Comment by guybedford** [comment]
I believe this issue was fixed in the latest SystemJS builder patch. Make sure you are running jspm 0.16.1.

**Comment by calvinfroedge** [comment]
```
jspm --version
0.16.1
Running against local jspm install.
```

**Comment by OliverJAsh** [comment]
Same problem here!

**Comment by guybedford** [comment]
@calvinfroedge if I follow your example exactly I get an ENOENT error loading `src/app` as it should be `app` that is bundled here with that configuration.

Running with that though, I see exactly the issue. Another subtlety of these defaultJSExtensions path rules, this time against plugin paths (it was detecting the path as `src/templates/*.jade.js`, missing classification and then double-normalizing).

I've added a fix in https://github.com/systemjs/builder/commit/6347cfe5f4f2d49d73e66b9c3d9831e4e3243ff1 which resolved the issue for me. @OliverJAsh let me know if that works for you as well, then I'll aim to post out a patch soon.

**Comment by OliverJAsh** [comment]
```
~/Development/frontend oja-jspm-16*
$ node bundle
Error: ENOENT, open '/Users/OliverJAsh/Development/frontend/static/src/javascripts/javascripts/projects/common/views/ui/loading.html'
    at Error (native)
^C

~/Development/frontend oja-jspm-16* 11s
$ cd node_modules/jspm && npm i systemjs/builder#6347cfe5f4f2d49d73e66b9c3d9831e4e3243ff1
npm WARN package.json jspm@0.16.1 license should be a valid SPDX license expression
systemjs-builder@0.13.4 node_modules/systemjs-builder
├── source-map@0.4.4 (amdefine@1.0.0)
└── es6-template-strings@1.0.0 (es5-ext@0.10.7)

~/Development/frontend/node_modules/jspm oja-jspm-16*
$ cd ../..

~/Development/frontend oja-jspm-16*
$ node bundle
```

That fixed it! :smile:

**Comment by guybedford** [comment]
:+1:
