### ISSUE TITLE
Please support NPM install

### ISSUE THREAD

**Issue by kburson** [systemjs/plugin-text#17]
As commented at the end of #6 the `package.json` is not fully formatted, it requires a 'name' key in order to be loaded by npm.  The `systemjs/plugin-json` loads fine, but `systemjs/plugin-text` does not.

**Comment by guybedford** [comment]
Sure, I'll happily take PRs for these types of changes.

**Comment by kburson** [comment]
I see that you already have one in your pull requests list by 'alanclarke ' on July 16.

**Comment by guybedford** [comment]
Thanks, it's actually from 2014 and the version is incorrect. I'm happy to include properties that make things easier, but I can't commit to publishing every release to npm, without doing it for all plugins and deprecating github as the plugin package registry.

**Comment by kburson** [comment]
I"m happy to help any way I can

**Comment by guybedford** [comment]
Am I right in thinking you want the npm name key just to enable `npm install git://github.com/systemjs/plugin-text`? If so I'm more than happy to take a new PR for that.

**Comment by dmmn** [comment]
Just added a little PR for it, I just need the git:// install as well.
https://github.com/systemjs/plugin-text/pull/18

Cheers and nice work btw ;)

**Comment by guybedford** [comment]
Thanks!
