### ISSUE TITLE
Using for ng-include

### ISSUE THREAD

**Issue by zeeshanjan82** [systemjs/plugin-text#21]
Can I use this plugin to include html file into my application which I am using ng-include in angularjs.

**Comment by divmgl** [comment]
You don't need to use `ng-include` if you're using this. Instead, create components (controllers, directives) and use the `template` property. 

If you want to do a bunch of includes in your code without creating a component for it, you can do something like this:

```javascript
import helloTemplate from './sometext.html!text'

angular.module('app').run(function($rootScope){
  $rootScope.helloTemplate = helloTemplate();
});
```
```html
<div>{{helloTemplate}}</div>
```
