### ISSUE TITLE
Using with all .html in a directory

### ISSUE THREAD

**Issue by mikehaas763** [systemjs/plugin-text#25]
Is it possible to set this loader to be used by system to be used by all *.html files in a directory and include all nested child *.html files?

**Comment by guybedford** [comment]
Yes, you can use a configuration like:

```javascript
System.config({
  meta: {
    'app/*.html': {
      loader: 'text'
    }
  }
});
```

Or alternatively use a [packages configuration](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages) meta in the above.

**Comment by mikehaas763** [comment]
@guybedford That doesn't work for nested html files though correct? At least it's not working for me. In your example above, I'd like to also match html files located in app/foo/bar/file.html

**Comment by guybedford** [comment]
@mikehaas763 wildcard meta uses deep wildcards so it does work for nested files, yes.

**Comment by mikehaas763** [comment]
@guybedford Strange. I've gone through `jspm init` basically using all the defaults except pointing to the right "server folder". I created a "global adapter" for angular because that import wasn't working quite right. Now I'm stuck on my html/text imports.

I've set a top level meta loader for "*.html" but I'm getting errors during bundle this:

> err  Error on fetch for crm/emails/emailTracking/emailTrackingListTemplate.html.js at /ccapp/crm/emails/emailTracking/emailTrackingListTemplate.html.js

**Comment by mikehaas763** [comment]
I'm currently looking into a theory that it may have to do with the `defaultJSExtensions` setting that jspm set up by default.

**Comment by mikehaas763** [comment]
I guess it's not possible to use defaultExtension within my app package and also use a loader to match against *.html?
