### ISSUE TITLE
HTML Tag Attribute Problem

### ISSUE THREAD

**Issue by lneffa** [systemjs/plugin-text#27]
This plugin is causing a problem for styling certain input fields in my html.

I have some .html files I can't seem to import properly.
When importing in my code using ``System.import('finance_apps/margin_pairing/filter-locations.html!text');```, I'm noticing a difference in the following input tags when comparing what gets imported and what the file actually holds.

From !text import:
```<input placeholder="Search Invoices" value.bind="currentSearch &amp; debounce" disabled.bind="!allowSearch">```

From html file:
```<input type="text" placeholder="Search Invoices" value.bind="currentSearch &amp; debounce" disabled.bind="!allowSearch"/>```

Notice the ```type="text"``` attribute is missing? Anyway to have this attribute included in the import?

**Comment by AdamBurgess** [comment]
This could be related to 0.0.5, although it's very peculiar that it would just remove that attribute...
If you install text@0.0.4, do you still encounter this bug?

**Comment by lneffa** [comment]
Thanks @AdamBurgess . I am closing this issue as I'm finding the problem isn't with this plugin.
I'll circle back if I'm still thinking it is and have more information.
