### ISSUE TITLE
Error when bundling text imports with jspm bundle

### ISSUE THREAD

**Issue by ben-8409** [systemjs/plugin-text#28]
I hope this is the right place for this report.

I am writing a ES6 Angular app and would like to use **imports** and jspm bundle with the **text plugin** to bundle the templates. However I get errors with my html imports:

`err  MultipleErrors: Error compiling esm module "app/modules/shop/view/shop.html!github:systemjs/plugin-text@0.0.5.js" at app/modules/shop/view/shop.html`

Just to be sure, i created a minimal example below:
_test.js_
`import html from 'test.html!text';`

_test.html_
`<h1>Test</h1>`

_config.js_
`System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "core-js": "npm:core-js@1.2.6",
    "text": "github:systemjs/plugin-text@0.0.5",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});`

_bundling_ leads to the following results:
`jspm bundle boot.js bundle.js
     Building the bundle tree for boot.js...
     
       boot.js
       test.html!github:systemjs/plugin-text@0.0.5/text
     

err  MultipleErrors: test.html:1:1: Unexpected token <
     test.html:1:2: Semi-colon expected
     test.html:1:10: Expected '/' in regular expression literal
`

**Comment by AdamBurgess** [comment]
could you post the contents of `jspm_packages/github/systemjs/plugin-text@0.0.5/text.js`?
