### ISSUE TITLE
jspm bundle fails to make sourcemap with plugin-text

### ISSUE THREAD

**Issue by blueshed** [systemjs/plugin-text#33]
Using jspm bundle with a text import causes the following error:

```
err  TypeError: Cannot read property 'match' of null
         at ./node_modules/systemjs-builder/lib/sourcemaps.js:62:25
         at Array.forEach (native)
         at SourceMapConsumer_eachMapping [as eachMapping] (./node_modules/source-map/lib/source-map-consumer.js:155:14)
         at ./node_modules/systemjs-builder/lib/sourcemaps.js:61:24
         at Array.forEach (native)
         at exports.concatenateSourceMaps (./node_modules/systemjs-builder/lib/sourcemaps.js:42:19)
         at createOutput (./node_modules/systemjs-builder/lib/output.js:63:21)
         at exports.writeOutputs (./node_modules/systemjs-builder/lib/output.js:150:16)
         at ./node_modules/systemjs-builder/lib/builder.js:607:14
       make: *** [build] Error 1
```

I'm using node 6.1.0 jspm 0.16.34 plugin-text 0.0.8. jspm is installed locally.

The build command is:  `jspm bundle appl/main dist/appl.js  -m`

```javascript
import "./main.scss!"
import tmpl from "./main.html!text"

import Vue from "vue"

var appl = new Vue({
	el: ".main",
	template: tmpl,
	data:{
		title: "Welcome"
	}
});
```

Removing the text import results in a successful build.

The workaround is to build without sourcemap using the option --skip-source-maps which isn't much of a workaround.

**Comment by divmgl** [comment]
This is happening to me as well. Any idea what could be causing this? This is pretty much a dealbreaker to convince my peers to adopt System.js.

**Comment by unicron** [comment]
+1 same problem here.  I added a try-catch within ./node_modules/systemjs-builder/lib/sourcemaps.js in the method that is failing, and it does complete.  Still, not ideal for including in a build pipeline with that hack.

**Comment by guybedford** [comment]
I was able to replicate this and added some fixes in https://github.com/systemjs/builder/commit/6ba5476e9e378f24ac98e96040adc4599c229479.

One of the things to note though is that Traceur is currently messing up source maps quite badly in the output which leads to strange bugs in the builder. I'd advise ensuring you use Babel for transpilation - `jspm dl-loader babel`.

**Comment by divmgl** [comment]
Thanks @guybedford much appreciated
