### ISSUE TITLE
jspm bundles text when it shouldn't

### ISSUE THREAD

**Issue by tyrsius** [systemjs/plugin-text#35]
I have a standard bundle setup with the jspm beta (0.17.0-beta.14). It works for javascript, but bundles text despite being instructed not to.

```
jspm bundle src/main.js - [src/**/*] - [devportal/**/*] dependencies.js --inject --skip-source-maps -d

     Building the bundle tree for src/main.js - [src/**/*] - [devportal/**/*]...
     
       devportal/guide/guide.md!github:systemjs/plugin-text@0.0.8/text.js
       ...
```

Note that I tried adding the ` - [devportal/**/*]` because ` - [src/**/*]` wasn't working (it should, since `devportal` is mapped from src`, and it works to filter out all the javascript in source.

Just in case it matters, here is the package map I am using.
```
"devportal": {
      "main": "main.js",
      "format": "esm",
      "map": {
        "./config/configBase.js": {
          "~production": "./config/config.dev.js",
          "production": "./config/config.prod.js"
        }
      }
```

**Comment by guybedford** [comment]
When using plugin syntax (as opposed to plugins via meta configuration), that is treated as an extension to the namespace. That is you would need to do `- [devportal/**/*!text]`.

**Comment by tyrsius** [comment]
Yep, there we go. Thank you =)
