### ISSUE TITLE
Bundled VS Src

### ISSUE THREAD

**Issue by JSlain** [systemjs/plugin-text#38]
Here's my imported resource:

`var template = require('app/components/home/home.tpl.html!text');`

If I directly serve my **src** folder, this call will make an http request to download the template file, and my `template` variable will contain the text.

If I bundle my application and serve the result, my `template` variable will contain something like:
`Object: {default: "<div>template content...</div>"}`

Is it the expected behavior?
How should I handle both?

**Comment by guybedford** [comment]
Thanks for explaining so clearly. I've included a correction in https://github.com/systemjs/plugin-text/commit/d003af5d52a03d5554ff0bb302ad1dc6d7f2c8cc. Let me know if that works for you here.

**Comment by JSlain** [comment]
Yeah, it simply works!
Thanks a lot.

**Comment by JSlain** [comment]
I mean, it'll work in the next release ;)

**Comment by guybedford** [comment]
Thanks for confirming, I've released a 0.0.9.
