### ISSUE TITLE
Can't import Angular2 Template

### ISSUE THREAD

**Issue by tom10271** [systemjs/plugin-text#39]
In Angular2 template, there are `[`, `]`, `{`, `}`, `;` etc.

When I compile codes and html with SystemBuilder it returns error, here is part of the error message:

```
token <
scripts/templates/index.tpl.html:1:2: Semi-colon expected
scripts/templates/index.tpl.html:1:2: Invalid left-hand side expression in assignment
scripts/templates/index.tpl.html:2:15: Unterminated String Literal
scripts/templates/index.tpl.html:3:14: Unexpected token :
scripts/templates/index.tpl.html:3:16: Unexpected token 'theme-black'
```

**Comment by RoxKilly** [comment]
Show more of your setup. I was just able to use this plugin to import and inline `Angular 2 rc.6` templates. You mention *"SystemBuilder"*; is  that [systemjs-builder](https://www.npmjs.com/package/systemjs-builder)? If so, I was able to use it to successfully bundle my app.

`typescript 2.0.2`, `Angular 2 rc.6`, `systemjs-builder 0.15.30`, `systemjs-plugin-text 0.0.9`

**Comment by aluanhaddad** [comment]
>
scripts/templates/index.tpl.html:3:16: Unexpected token 'theme-black' scripts/templates/index.tpl.html:1:2: Semi-colon expected
>

This sounds like it is being picked up by the wrong loader, specifically that is being parsed as TypeScript or JavaScript. Make sure you configured systemjs-plugin-text to load html files. See the following for an example:
```JavaScript
SystemJS.config({
  meta: "*.html" {
    "loader": "text"
  }
});
```

**Comment by tom10271** [comment]
@RoxKilly How do you import html?

like this: `import './templates/nav.tpl.html!text';`? Yes I am using SystemJs Builder.

    "jspm": "0.16.29",
    "jspm-npm": "0.26.7",
    "systemjs-builder": "0.14.15",
    "typescript": "1.7.3"

SystemJs config:
```
  packages: {
    "scripts/templates": {
      "main": ".",
      "defaultExtension": "html"
    },
    "scripts": {
      "main": ".",
      "defaultExtension": "ts"
    }
  },

  meta: {
    "*.html": {
      "loader": "text"
    }
  },
```

**Comment by tom10271** [comment]
@aluanhaddad I am importing it from a `.ts` file under /scripts folder, will it affect which loader loading the template? I still can't load it with this plugin when loading templates after adding the config you gave.

**Comment by tom10271** [comment]
After upgrading SystemJS Builder to `0.15.32`, bundling HTML is now supported.

Thanks guys

**Comment by RoxKilly** [comment]
@tom10271  could you provide a link to instructions please?

**Comment by aluanhaddad** [comment]
@RoxKilly package configuration and plugin syntax are different ways to accomplish the same goal. Package configuration is preferred in which case you would write. 

`import template from './my-template.html';` or without the extension if you have it configured as the default.

Looks like you're using an old version of type script. You should be using 1.8.10 at minimum.

**Comment by RoxKilly** [comment]
@aluanhaddad  Thanks.  I'm using `typescript 2.0.2` and package configuration to import HTML and CSS as text. This is working well.

**systemjs.config.js**
```
System.config({
	map:{
		app: 'dist',
		'systemjs-plugin-text': 'node_modules/systemjs-plugin-text/text.js',
	},
	packages:{
		app: {
			main: './main.js',
			meta:{'*.html': {'loader': 'systemjs-plugin-text'}}
		}
	}
});
```
From @tom10271 's comment:
> After upgrading SystemJS Builder to 0.15.32, bundling HTML is now supported

I thought he meant that there is no need for a special loader.  That's what I was asking about

**Comment by aluanhaddad** [comment]
@RoxKilly Yeah, that confused me as well. Regardless you configuration looks great.
