### ISSUE TITLE
Since 0.17-beta-30, text module json is not found runtime after a 'bundle'

### ISSUE THREAD

**Issue by stephanbureau** [systemjs/plugin-text#41]
Hi,

Since the jspm beta-30 and 31, I found a missing registerDynamic call within my 'bundle' js file. This makes my whole application crashing at runtime as it tries to get the plugin-text json but it is never defined.
Code missing used to look like this in my beta-29 bundle:
```
System.registerDynamic("github:systemjs/plugin-text@0.0.8.json", [], false, function() {
  return {
    "main": "text"
  };
});
```
Not sure if this is directly linked to this plugin or not, but this is the only piece of code that blocks me to use latest jspm beta versions right now.

Update: For now, I am ok with beta-29, this is not blocking me.

**Comment by guybedford** [comment]
Thanks. Can you share any isolated replication of this issue?

**Comment by stephanbureau** [comment]
Np, yes I'll try to create a dedicated repo during the weekend, as I can't share the company code.
Thanks.

**Comment by stephanbureau** [comment]
After trying latest jspm with almost same context in https://github.com/UIUXEngineering/angular2-jspm-typescript-seed, I am not able to reproduce nor isolate the error. Closing the issue for now.
