### ISSUE TITLE
Using </script> inside html causes "Uncaught SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by sergueyarellano** [systemjs/plugin-text#42]
First of all, thanks for the tools, having a great time!

file template.html
`<script>...</script>`

file main.js
`import template from 'template.html!text'`

importing 'template.html!text' is working great without bundling

Even without "!text", configuring:

`packages: {
    "test/lib/html": {
      defaultExtension: false,
      meta: {
        "*.html": {loader: 'text'}
      }
    }
  }`

In the other hand, when I do "jspm bundle-sfx main.js" I'm having this issue when executing it.

If I modify template.html
`<script>...<\/script>` or just `<script>...`

It works again, but I am not allowed (at work) to modify those files.

Thanks for the support

**Comment by guybedford** [comment]
Can you share the bundle js file that is giving an error here?

**Comment by sergueyarellano** [comment]
I'm using this script to execute the build:

"jspm build app.js && less build.js | testling --no-show --bcmd=\"/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome\""

https://github.com/sergueyarellano/plugin-text-issue/blob/master/build.js#L7352

**Comment by guybedford** [comment]
@sergueyarellano it looks like `build.js` loads fine in a browser to me - you will only have problems if you inline that into a `<script>` tag as the `</script>` messes with the HTML parser then.

**Comment by sergueyarellano** [comment]
thanks @guybedford, that seems to be the problem ;)

Any workaround here? I'm stuck with this...

**Comment by guybedford** [comment]
When inlining JS into HTML you need to apply some escaping rules. Whatever tool is generating your inline script should be doing this for you. The simple approach is to directly string replace `<` with `\u003c`.

**Comment by sergueyarellano** [comment]
Thank you very much I'll take that approach and tell. :)

**Comment by sergueyarellano** [comment]
When requiring HTML files with plugin-text and "bundle-sfx" against "testling" is necessary to escape `<` in HTML script tags.

https://ci.testling.com/
