### ISSUE TITLE
jspm install text bad response code 404

### ISSUE THREAD

**Issue by ivanbacher** [systemjs/plugin-text#46]
When trying to install this plugin via JSPM, i keep on receiving a 404 error. However, when trying to install the css plugin not error occurs.

![screen shot 2017-03-22 at 15 26 20](https://cloud.githubusercontent.com/assets/5493114/24205677/f4e656f4-0f13-11e7-88c2-a3fd447022e1.png)

**Comment by guybedford** [comment]
Can you download anything from GitHub with jspm? Are the GitHub credentials working correctly?

**Comment by ivanbacher** [comment]
Yes I am able to download the css plugin via Github, but getting the same error on other repositories. Anyway, i created a new access token on Github and that seemed to solve the issue 🤦🏻‍♂️.

**Comment by nym** [comment]
Does your personal access token on github have the private_repros setting checked?
