### ISSUE TITLE
How to use this plugin correctly?

### ISSUE THREAD

**Issue by crooksey** [systemjs/plugin-text#49]
I have a basic systemjs-builder plugin that bundles all my Angular TS code, such as:
```javascript
var SystemBuilder = require('systemjs-builder');
var argv = require('yargs').argv;
var builder = new SystemBuilder();

builder.loadConfig('./systemjs.config.js')
  .then(function(){
          var outputFile = argv.prod ? 'dist/bundle.min.js' : 'dist/bundle.js';
          return builder.buildStatic('app', outputFile, {
                  minify: true,
                  mangle: true,
                  rollup: argv.prod,
                  encodeNames:false
          });
  })
  .then(function(){
          console.log('bundle built successfully!');
  });
```

In my systemJs configs I have:

under map section:
```javascript
'text': 'npm:systemjs-plugin-text/text.js'
```
Then a separate:
```javascript
meta: {
            "*.html": {
            "loader": "text"
            }
        },
```

In my app structure I have components and templates such as:
```typescript
@Component({
    moduleId: module.id,
    templateUrl: 'mytemplate.html'
})
export class MyComponent implements OnInit {
    constructor() {}
    ngOnInit() {
        // Awesome code goes here
    }
}
```

```html
<div>
    <mySelector></mySelector>
</div>
```

How do I actually use/call this plugin to bundle all my html code inside my newly created bundle.js?

**Comment by aluanhaddad** [comment]
Greetings. All of your configuration is correct you just need to make the following adjustments.

Instead of using `templateUrl` which the Angular documentation explicitly excludes from its SystemJS support for some reason (writing a plug-in would be fairly straightforward), you need to use the `template` property of the component decorator factory and the ES module syntax.

Here is how I would write it:
```ts
import template from './mytemplate.html';
import style from './mystyle.css';

@Component({
  template,
  styles: [style]
}) export class MyComponent {}
```

This is actually rather elegant as it frees you from dependence on the details of specific loaders and bundlers because it doesn't rely on `moduleName` or `moduleId` neither of which are portable. In fact the code above will work with other tool chains without the need to rewrite. It also enables greater flexibility in structuring your directories since your templates are simply es modules.

**Comment by crooksey** [comment]
Thanks @aluanhaddad  that makes sense, but both typescript (and javascript) throw an error when trying to use this style, mainly: "cannot find mytemplate.html" even though its there, do I need to do/enable anything else to structure my app this way?

**Comment by crooksey** [comment]
Ok so in my typescript modules.d.ts I added:
```
declare module "*.html" {
    const content: string;
    export default content;
}
```
Then in my component I now have:
```
import myTemplate from './app.component.html'

@Component({
    selector: 'app',
    template: myTemplate,
})
```

This compiles without error, however on load of the browser I get the error:
```
Error: No template specified for component AppComponent
  Evaluating http://localhost:3000/app/main.js
  Loading app
    at syntaxError (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
    at DirectiveNormalizer.normalizeTemplate (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14130:19)
    at CompileMetadataResolver.loadDirectiveMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:15161:75)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:26838:72)
    at Array.forEach (native)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:26837:72)
    at Array.forEach (native)
    at JitCompiler._loadModules (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:26834:75)
    at JitCompiler._compileModuleAndComponents (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:26804:36)
    at JitCompiler.compileModuleAsync (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:26733:37)
```

Do I need to add/enable anything else?

**Comment by aluanhaddad** [comment]
Make sure you're using `"module": "system"` in your typescript configuration.

**Comment by mlc-mlapis** [comment]
@crooksey ... it is possible to keep `"module": "commonjs"` but you have to modify `systemjs-plugin-text/text.js` code because TS compiler transpiles source code:
```
import myTemplate from './app.component.html'

@Component({
    selector: 'app',
    template: myTemplate,
})
```
to something like **`template: my_template_1.default`** but the HTML code is located in `my_template_1` -> which is the returned value from `systemjs-plugin-text/text.js`.

**Comment by aluanhaddad** [comment]
@mlc-mlapis that's true, and another option is also to use one of es module transpiler plugins, but angular users seem to go to great lengths to avoid that option, even though it works.

**Comment by mlc-mlapis** [comment]
@aluanhaddad ... you are right also. 👏 But the problem in this case is that `ngc` isn't able to take the template by that way (`import` or transpiler plugins).

**Comment by aluanhaddad** [comment]
Goodpoint, I didn't think of that.

`ngc` is one of those things from which I run screaming.

**Comment by crooksey** [comment]
Thanks very much, i now have this working, I had to extend the text.js to (as pointed out by @mlc-mlapis  in gitter):
```javascript
  load.metadata.format = 'amd';
  load.metadata.esModule = true;
  return 'def' + 'ine(function() {\nreturn { default: ' + JSON.stringify(load.source) + ' };\n});';
```
I still kept using commonjs and could remove the "module.id" from my components, hopefully this can help future angular users that want to bundle/use this plugin.
