### ISSUE TITLE
Usage with SystemJS 3.0.0

### ISSUE THREAD

**Issue by while0pass** [systemjs/plugin-text#52]
It would be great if one can use the plugin with SystemJS 3.0.0 to lazy load text file into a variable.

**Comment by guybedford** [comment]
This plugin could certainly be upgraded to support SystemJS 3.0.0.

We haven't yet worked out if we want to stick with `./file!text` as the specifier form, use configuration, or another approach to import text, so working out the best approach for this in SystemJS 3.0.0 would be a prerequisite for that.

What is the use case you had in mind here?

**Comment by while0pass** [comment]
Thank you for your response. I suppose the issue can be closed, as it's rather easy to use XMLHttpRequest API or Fetch API for the purpose of populating a variable from a text file through lazy loading.
