### ISSUE TITLE
EXPORTS is not defined?!!!

### ISSUE THREAD

**Issue by CNSKnight** [systemjs/plugin-text#53]
Why does this plugin literally NOT work w/"0.21.6"
```
GET http://localhost:9000/favicon.ico 404 (Not Found)
text.js:4 Uncaught ReferenceError: exports is not defined
    at text.js:4
(anonymous) @ text.js:4
```
I see NO documentation to support that 0.21 should NOT support existing plugins?!!!

**Comment by guybedford** [comment]
Thanks for the ping! https://github.com/systemjs/plugin-text/commit/1b15a414f8a6c39543e41fe41f06b967ba81e5b9

Open source is what you make it.
