### ISSUE TITLE
Error loading HTML files

### ISSUE THREAD

**Issue by BuildingJarl** [systemjs/plugin-text#7]
`import template from './template.html!text'` used to work for importing html files, but today i have noticed that this approach is no longer working. When starting the server with live-server, the following error is output to the console.

throws error using live-server

`Error: Requested Range Not Satisfiable
    at SendStream.error (/Users/Iv/.nvm/v0.10.29/lib/node_modules/live-server/node_modules/send/index.js:245:16)
    at SendStream.send (/Users/Iv/.nvm/v0.10.29/lib/node_modules/live-server/node_modules/send/index.js:540:19)
    at onstat (/Users/Iv/.nvm/v0.10.29/lib/node_modules/live-server/node_modules/send/index.js:600:10)
    at Object.oncomplete (fs.js:107:15)`

but if the .html extension is changed to a .txt extension, and this import is made `import template from './template.txt!text` everything works as expected.

This error get displayed all the time though. So i tested the following:
```
import template from './test.txt!text';
console.log("hello") // prints to console

import template from './test.html!text';
console.log("hello") //does not get printed
```

or

```
import template from './test.txt!text';
console.log(template) // prints content of file

import template from './test.html!text';
console.log(template) //does not get printed
```

![screen shot 2015-02-24 at 16 41 19](https://cloud.githubusercontent.com/assets/5493114/6353923/130bc01c-bc44-11e4-857a-9d26446dfb98.png)

**Comment by guybedford** [comment]
Interesting, does it work if it is `test.htm` instead of `test.html`?

**Comment by BuildingJarl** [comment]
no, makes no difference.

**Comment by guybedford** [comment]
The content length mismatch seems like a network error somehow? Perhaps look at the network tab?

**Comment by BuildingJarl** [comment]
I tried to replicate the error again, but with no luck. Everything seems to be working again now. I think it was probably just some problem with my setup.

**Comment by danharper** [comment]
I was getting the same problem using [`live-server`](https://github.com/tapio/live-server).

Seems it's trying to inject the live-reload script into `.html` files, and failing miserably. Chrome wasn't showing _any_ errors, and Firefox was showing `Error: Requested Range Not Satisfiable`.

Renaming template extensions, or using a different server fixes it.
