### ISSUE TITLE
Have you ever seen issues using this with karma?  I seem to get a 404.

### ISSUE THREAD

**Issue by robcleghorn** [systemjs/plugin-text#8]

**Comment by guybedford** [comment]
Yes this is the karma-jspm works - see https://github.com/Workiva/karma-jspm/issues/41 and https://github.com/Workiva/karma-jspm/issues/24 for some guidance.

**Comment by robcleghorn** [comment]
I don't think these are related, everything else is running fine, it's specifically when I import using !text karma does a 404 even though the path looks correct.

**Comment by guybedford** [comment]
Can you load the same path manually in the browser?

**Comment by robcleghorn** [comment]
Found it I needed to add html file to my watch in the karma-jspm config
```javascript
jspm: {
            // Edit this to your needs
            config:'src/config.js',
            serveFiles: [
                'src/**/!(*.spec).js',
                'src/**/*.html',
                'node_modules/rtts-assert/dist/es6/assert.js'],
            loadFiles: ['src/**/*.spec.js']
        }
```

**Comment by guybedford** [comment]
Glad you sorted it out.

**Comment by Quirksmode** [comment]
This really helped me, thanks
