### ISSUE TITLE
Wrong request path?

### ISSUE THREAD

**Issue by dmackerman** [systemjs/plugin-text#9]
I'm trying to import an `html` file for use inside an Angular application - let me preface this by saying I have to idea if this is best practice or not.

```js
import loginTemplate from 'app/login/login.tpl.html!text';
```

The request that gets made:

![das](https://dl.dropboxusercontent.com/spa/pkr1d5uhq1t8wz1/v6dc4g7l.png)

Am I doing something wrong here? Is it recommended that we precompile these into JS modules? Trying to avoid that build step if I can just import them directly. :)

**Comment by dmackerman** [comment]
Sorry, it appears that I didn't install the plugin and map it properly. For others:

`jspm install github:systemjs/plugin-text`,

and in the config:

`"text": "github:systemjs/plugin-text@0.0.2"`

**Comment by guybedford** [comment]
Glad you sorted it out. `jspm install text` will ensure the right configuration without any other changes. See https://github.com/jspm/jspm-cli/wiki/Plugins#using-plugins for more info on plugins.
